### ISSUE TITLE
add sea cucumber facts

### ISSUE THREAD

**Issue by joel-g** [joel-g/animal-facts-bot#106]

**Comment by kburk1997** [comment]
Is this still unclaimed? Because I can get on this

**Comment by joel-g** [comment]
@kburk1997 yes it's unclaimed. I just added it 20 minutes ago because a redditor tried to ask the bot about cucumbers.

**Comment by kburk1997** [comment]
Ok, I'll claim it right now. I already forked it

**Comment by kburk1997** [comment]
see pull request #108
