### ISSUE TITLE
Ostrich

### ISSUE THREAD

**Issue by melvyniandrag** [joel-g/animal-facts-bot#135]
We need ostriches!

**Comment by airbos994** [comment]
I'm working on it

**Comment by melvyniandrag** [comment]
btw, change
\sostrich?\s 
to
\sostrich(es)?\s 

If you want to know why: That's a pattern match, it looks on reddit for any occurence of ostrich or ostrich+es. 

and remember, after making changes:
git add -A
git commit -m "a meaningful message about the files I've changed and why I've changed them."
git push origin master

You can see the bot in action here:
https://www.reddit.com/r/3Dprinting/comments/764wla/gluing_pla_prints/dobm2at/?context=3
The person mentions a gorilla and the bot replies with a gorilla fact.
