### ISSUE TITLE
Anteater facts

### ISSUE THREAD

**Issue by melvyniandrag** [joel-g/animal-facts-bot#149]
In need of anteater facts. 

This project is I think one of the best ones for hacktoberfest. It's easy and it does something cool in the real world!

**Comment by andrew-jung** [comment]
I'll find some anteater facts if still open! 8)

**Comment by joel-g** [comment]
@melvyniandrag I'm glad you think so. I've been blown away by the number of people participating.
@andrew-jung go for it!
