### ISSUE TITLE
Add orca facts

### ISSUE THREAD

**Issue by joel-g** [joel-g/animal-facts-bot#21]
Teach AnimalFactsBot about orcas

**Comment by xdizzaster** [comment]
I'll take it!

**Comment by nrabins** [comment]
@xdizzaster I started work on this, here are the facts I found before I saw that you claimed it. :)

"The orca is called the 'killer whale' due their ability to take down large marine animals, such as sea lions and whales.",
    "An orca's teeth can grow to be 4 inches (10 cm) long.",
    'The orca can reach speeds in excess of 30 knots (about 34 mph, or 56 kph).',
    'Orcas can weigh up to 6 tons.',
    'The largest orca ever recorded was 32 geet long.'

**Comment by xdizzaster** [comment]
@nrabins Thanks for the facts, I'll update the PR to include the ones I didn't find. Sorry for taking the issue from you :(

**Comment by nrabins** [comment]
@xdizzaster No problem at all, I didn't claim it.
