### ISSUE TITLE
Read through facts strings and make sure every fact mentions the animal species itself

### ISSUE THREAD

**Issue by joel-g** [joel-g/animal-facts-bot#292]
Good example: "Rabbits are soft"
Bad example: "They are soft"

**Comment by danyelcampbell** [comment]
I would like to work on this!

**Comment by mpentler** [comment]
Thank fuck for that I was worried I might have to do it! 😜

**Comment by danyelcampbell** [comment]
Hah, I don't mind going through and editing stuff, I'm free for the next like 2 hours anyways

**Comment by danyelcampbell** [comment]
I'm gonna edit for grammar as well, can't do this in good faith with these sentences in such a state D:

**Comment by danyelcampbell** [comment]
so it took me 2 weeks but I did it! <3

**Comment by mpentler** [comment]
You beautiful man

On 16 Feb 2018, at 22:11, Danyel Campbell <notifications@github.com<mailto:notifications@github.com>> wrote:


so it took me 2 weeks but I did it! <3

**Comment by joel-g** [comment]
Not all heroes wear capes

**Comment by danyelcampbell** [comment]
I'll be happy to run through it again whenever more facts are added <3
